### ISSUE TITLE
Issue merging Archer fusions in Archer only cohort?

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/cmo-pipelines#716]
Here is a patient in MSK-IMPACT that has archer fusions that are properly displayed:

[mskimpact-cohort](https://cbioportal.mskcc.org/patient?studyId=mskimpact&caseId=P-0027086#navCaseIds=mskimpact:P-0027086)

but in the Archer only cohort an error is thrown.  Do we properly merge fusion data in the Archer only cohort into the mutation profile?

[archer-cohort](https://cbioportal.mskcc.org/patient?studyId=mskarcher&caseId=P-0027086#navCaseIds=mskarcher:P-0027086)

I noticed that sometimes there is an error message:

![image](https://user-images.githubusercontent.com/366003/79901939-a5735980-83de-11ea-9a36-190eb9bdde83.png)

and sometimes there is an empty patient view:

![image](https://user-images.githubusercontent.com/366003/79902122-ec614f00-83de-11ea-8c31-0a5064674b4f.png)

**Comment by ao508** [comment]
Created an issue in the frontend https://github.com/cBioPortal/cbioportal-frontend/issues/3275

Shared direct links to the same patient's patient view page in the gdac mskimpact study and the triage `mskarcher_test` study with Onur.

**Comment by ao508** [comment]
Confirmed with Onur that this is a frontend issue with how variants are filtered/displayed on frontend in mutation table.

**Comment by ao508** [comment]
At this time there is nothing else for us to do - when the fix is in place we will need to update the `meta_fusions.txt` file for the archer only cohort.  (stable id, genetic alteration type need updating)

**Comment by ao508** [comment]
Ritika shared that genes with fusions table on study summary page does not render for ARCHER only cohort.

**Comment by ao508** [comment]
There's an ongoing conversation in the issue linked above regarding the proper way to handle the ARCHER only cohort.

**Comment by ao508** [comment]
@n1zea144 I wanted to make a quick note - the patient linked above does not have any ARCHER fusion events, just fusion events reported by the IMPACT pipeline.

**Comment by ao508** [comment]
Here is a patient that has ARCHER events:

https://cbioportal.mskcc.org/patient?studyId=mskimpact&caseId=P-0000104#navCaseIds=mskimpact:P-0000104


https://cbioportal.mskcc.org/patient?studyId=mskarcher&caseId=P-0000104#navCaseIds=mskarcher:P-0000104

@n1zea144 The ARCHER fusion event displays in both cohorts for this patient so I'm not sure if there is an error to address after all? 

The example patient that I was using as a reference above does not have ARCHER fusion events so that led me to believe that the frontend was incorrectly omitting the fusion records from the patient view mutation table.
